name: 'Initalize Bit'
description: 'Initialize Bit'
icon: download
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
    default: './'
runs:
  using: 'node16'
  main: 'dist/index.js'
