name: 'Initialize Bit'
description: 'Initialize Bit'
branding: 
  icon: 'download'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
    default: './'
runs:
  using: 'node20'
  main: 'dist/index.js'
